name: deploy

on:
  push:
    paths:
      - '.github/workflows/**'
      - 'backend/src/**'
      - 'backend/build.gradle'
      - 'backend/settings.gradle'
      - 'Dockerfile'
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop  # ðŸ”¥ PRë„ ì¶”ê°€ (í…ŒìŠ¤íŠ¸ ëŒë¦¬ê¸° ìœ„í•´)

env:
  DOCKER_IMAGE_NAME: schs
  SPRING_PROFILES_ACTIVE: test

jobs:
  backend-ci:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ‘‹ Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 1

      - name: â˜•ï¸ Set up JDK 21
        uses: actions/setup-java@v4.7.0
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: ðŸ” Grant execute permission for gradlew
        run: chmod +x ./gradlew
        working-directory: backend/project2/
        shell: bash

      - name: ðŸ’Š Start Redis
        uses: supercharge/redis-github-action@1.7.0
        with:
          redis-version: 7

      - name: ðŸ›  Build with Gradle with test profile
        run: ./gradlew build -Pprofile=test
        working-directory: backend/project2/
        shell: bash

      - name: ðŸ“„ Upload test report if it exists  # âœ… í…ŒìŠ¤íŠ¸ ë¦¬í¬íŠ¸ ì—…ë¡œë“œ
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: backend/build/reports/tests/test/
          if-no-files-found: ignore

  buildImageAndPush:
    name: ë„ì»¤ ì´ë¯¸ì§€ ë¹Œë“œì™€ í‘¸ì‹œ
    needs: makeTagAndRelease
    runs-on: ubuntu-latest
    outputs:
      owner_lc: ${{ steps.export_owner.outputs.owner_lc }}
      image_name: ${{ steps.export_image.outputs.image_name }}
    steps:
      - uses: actions/checkout@v4

      - name: â˜•ï¸ Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: ï¸â˜•ï¸ Grant execute permission for gradlew
        run: chmod +x ./gradlew
        working-directory: ./backend

      - name: ðŸ§ª í…ŒìŠ¤íŠ¸ ì½”ë“œ ë¹Œë“œ & ì‹¤í–‰
        run: ./gradlew test -Dspring.profiles.active=test
        shell: bash
        working-directory: ./backend

      - name: application-secret.yml ìƒì„±
        env:
          APPLICATION_SECRET: ${{ secrets.APPLICATION_SECRET }}
        run: echo "$APPLICATION_SECRET" > src/main/resources/application-secret.yml

      - name: Docker Buildx ì„¤ì¹˜
        uses: docker/setup-buildx-action@v2

      - name: ë ˆì§€ìŠ¤íŠ¸ë¦¬ ë¡œê·¸ì¸
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: set lower case owner name
        id: export_owner
        run: |
          OWNER_LC="${GITHUB_REPOSITORY_OWNER,,}"
          echo "owner_lc=$OWNER_LC" >> $GITHUB_OUTPUT

      - name: export image name
        id: export_image
        run: echo "image_name=app250416" >> $GITHUB_OUTPUT

      - name: ë¹Œë“œ ì•¤ í‘¸ì‹œ
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.export_owner.outputs.owner_lc }}/${{ steps.export_image.outputs.image_name }}:${{ needs.makeTagAndRelease.outputs.tag_name }},
            ghcr.io/${{ steps.export_owner.outputs.owner_lc }}/${{ steps.export_image.outputs.image_name }}:latest

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: [ buildImageAndPush ]
  #   steps:
  #     - name: AWS SSM Send-Command
  #       uses: peterkimzz/aws-ssm-send-command@master
  #       id: ssm
  #       with:
  #         aws-region: ${{ secrets.AWS_REGION }}
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         instance-ids: "i-02dd41bd1fdad46a8"
  #         working-directory: /
  #         comment: Deploy
  #         command: |
  #           docker pull ghcr.io/${{ needs.buildImageAndPush.outputs.owner_lc }}/${{ needs.buildImageAndPush.outputs.image_name }}:latest && \
  #           docker stop app1 2>/dev/null || true && \
  #           docker rm app1 2>/dev/null || true && \
  #           docker run -d --name app1 -p 8080:8080 ghcr.io/${{ needs.buildImageAndPush.outputs.owner_lc }}/${{ needs.buildImageAndPush.outputs.image_name }}:latest && \
  #           docker rmi $(docker images -f "dangling=true" -q) || true
